GET http://localhost:5000/

###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
  "name": "Sylvia Cobb",
  "email": "olripwez@me.bg",
  "password": "b0a8863f-740d-4518-8800-81e9a390d3ae"
}

###
POST http://localhost:5000/api/user/auth

###
POST http://localhost:5000/api/user/logout

###
GET http://localhost:5000/api/user/profile

###
PUT http://localhost:5000/api/user/profile
