GET http://localhost:5000/

###
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "name": "user1",
  "email": "user1@test.com",
  "password": "123"
}

### LOGIN
POST http://localhost:5000/api/users/auth
Content-Type: application/json

{
  "email": "John@gmail.com",
  "password": "123"
}

###
POST http://localhost:5000/api/users/logout

###
GET http://localhost:5000/api/users/profile
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc4MjM0ZDExZTRhZWRlYWZhNjkxOTUiLCJpYXQiOjE2ODU1OTg0MjgsImV4cCI6MTY4ODE5MDQyOH0.iJeMHPGSJ4Q5sf5whUn3vxS2V5-jArsmMxcDGYDDBgI

###


###
PUT http://localhost:5000/api/users/profile
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc4MjM0ZDExZTRhZWRlYWZhNjkxOTUiLCJpYXQiOjE2ODU1OTg0MjgsImV4cCI6MTY4ODE5MDQyOH0.iJeMHPGSJ4Q5sf5whUn3vxS2V5-jArsmMxcDGYDDBgI

{
  "name": "John",
  "email": "John@gmail.com",
  "password": "123"
}