GET http://localhost:5000/

###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
  "name": "Sylvia Cobb",
  "email": "olripwez@me.bg",
  "password": "b0a8863f-740d-4518-8800-81e9a390d3ae"
}

### LOGIN
POST http://localhost:5000/api/user/auth
Content-Type: application/json

{
  "email": "John@gmail.com",
  "password": "123"
}

###
POST http://localhost:5000/api/user/logout

###
GET http://localhost:5000/api/user/profile
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc4MjM0ZDExZTRhZWRlYWZhNjkxOTUiLCJpYXQiOjE2ODU1OTg0MjgsImV4cCI6MTY4ODE5MDQyOH0.iJeMHPGSJ4Q5sf5whUn3vxS2V5-jArsmMxcDGYDDBgI

###


###
PUT http://localhost:5000/api/user/profile
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc4MjM0ZDExZTRhZWRlYWZhNjkxOTUiLCJpYXQiOjE2ODU1OTg0MjgsImV4cCI6MTY4ODE5MDQyOH0.iJeMHPGSJ4Q5sf5whUn3vxS2V5-jArsmMxcDGYDDBgI

{
"name":"John",
"email":"John@gmail.com",
"password":"123"
}